name:                diceprob
version:             0.0.1
github:              "Time0o/diceprob"
license:             MIT
author:              "Timo Nicolai"
maintainer:          "timonicolai@earcor.de"
copyright:           "2020 Timo Nicolai"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Time0o/diceprob>

dependencies:
- base >= 4.7 && < 5
- cmdargs
- hspec
- ieee754
- megaparsec
- parser-combinators
- replace-megaparsec
- text
- transformers
- unordered-containers

library:
  source-dirs: src

executables:
  diceprob:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diceprob

tests:
  diceprob-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diceprob
